### PR TITLE
define variables for playlists

### PR DESCRIPTION
**Pull request by BolajiOlajide**
This PR will help set up automation with Duke such that when a new playlist is launched, we can update the website via Duke.

There's a lot of formatting here because my editor auto-formats HTML and I think it's a bit more readable (at least for me) like this. However, the major change is in the new `script` tag I added.

### CODE REVIEW

**Review by timigod — COMMENTED** [review]
@BolajiOlajide a few things:

- Can we see a loom video so that it's easy to visualise how this works. I like to do that with PRs?

- Have we given any thought to who can trigger this? Ideally, not anybody in the discord should be able to update the website. How are you thinking about this?

**Comment by BolajiOlajide** [comment]
> @BolajiOlajide a few things:
> 
> * Can we see a loom video so that it's easy to visualise how this works. I like to do that with PRs?
> * Have we given any thought to who can trigger this? Ideally, not anybody in the discord should be able to update the website. How are you thinking about this?

1. Yea, I like to do that too. Adding a loom / screenshot - however, this PR doesn't add any visual change. It just abstracts the links to a variable so that Duke can update easily.
2. Yes, Duke will handle that permission. Only folks with `Administrator` permission will be able to use the `/website` command.

@timigod

**Comment by timigod** [comment]
@BolajiOlajide I guess what the loom would show would be the links changing whenever the command is used.

**Review by timigod — APPROVED** [review]

**Comment by BolajiOlajide** [comment]
> @BolajiOlajide I guess what the loom would show would be the links changing whenever the command is used.

The command for changing the links doesn't live here. It lives in Duke. There's no visual change here.
This is just a structural change that'll enable Duke to make the changes - the loom will be in the PR for Duke not here.

**Comment by timigod** [comment]
> > @BolajiOlajide I guess what the loom would show would be the links changing whenever the command is used.
> 
> 
> 
> The command for changing the links doesn't live here. It lives in Duke. There's no visual change here.
> 
> This is just a structural change that'll enable Duke to make the changes - the loom will be in the PR for Duke not here.

Ah, unless you've not made the change in Duke. But if you have, then you can demo despite the command living in duke's repo.

**Pull request merged**
